language: go

go:
  - 1.11.x

os:
  - linux
  - osx

before_install:
  - go get github.com/mattn/goveralls

env:
  - GO111MODULE=on

script:
  - go build -v
  - go test -v -cover -race
  - goveralls -v
